To: to-example@example.com
From: from-example@example.com
Subject: Basic text-only email
Content-type: text/html

<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc nec dolor sodales, efficitur augue a, iaculis tellus. Duis nec nunc ac nibh ornare sagittis. Curabitur nec vestibulum nibh, a pellentesque turpis. Donec fringilla ligula et iaculis interdum. Integer eleifend id elit quis rhoncus. Pellentesque ex mi, egestas nec nunc vel, mollis imperdiet metus. Nulla fermentum dolor ac posuere aliquam. Cras commodo tristique viverra. Phasellus non malesuada nulla. Integer blandit, orci a sagittis ultrices, arcu enim ultricies tortor, sed eleifend augue ante non ipsum. Integer vestibulum eget lorem in molestie. Curabitur ex libero, egestas malesuada felis vel, fermentum pellentesque nulla. Nunc vel pharetra nunc. Donec sollicitudin, ex nec pulvinar feugiat, nisl diam pretium lacus, vitae eleifend ex lorem vel ligula. Proin tincidunt magna eu ante convallis aliquam. Suspendisse lacinia enim metus, sit amet fermentum quam eleifend sed.
</p>
